os: linux
dist: bionic
language: python
python: 3.8
cache: pip
before_script:
  - pip install --upgrade pip
  - sudo pip install linkchecker
script: |
  linkchecker https://devjugal.com
  linkchecker https://til.devjugal.com
