name: Docker Builder

on:
  workflow_dispatch:
    inputs:
      GIT_URL:
        description: "Git URL"
        default: "https://bitbucket.org/yalan_bb/internet_test_tools.git"
        required: true
      BRANCH:
        description: "Branch To Clone"
        default: "master"
        required: true

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        run: git clone "${{ github.event.inputs.GIT_URL }}" --branch "${{ github.event.inputs.BRANCH }}"

      - name: Build Docker Image
        run: |
          cd internet_test_tools
          if [[ ! -f "Dockerfile" ]]; then exit 1; else docker build -t crazyuploader/internet_test_tools:latest .; fi

      - name: DockerHub Login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: |
          docker images | grep internet_test_tools
          docker push crazyuploader/internet_test_tools
