name: Links

on:
  push:
    branches:
      - devjugal-links-checker
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker for devjugal.com
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            https://devjugal.com --verbose --accept 999
          format: markdown
          jobSummary: true
          output: lychee/results.md

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/results.md
          labels: report, automated issue
